### ISSUE TITLE
Invalid relative instructions size estimation

### ISSUE THREAD

**Issue by es3n1n** [zyantific/zasm#100]
Hello, first of all, thanks for all that huge work, but there are some problems with program size estimation that I want to report and maybe help you fix it.

In the example below I've used the `estimateCodeSize` and `allocatePage` from the `basic_jit` example.
```cpp
static std::size_t estimate_code_size(const zasm::Program& program) {
    std::size_t size = 0;
    for (auto* node = program.getHead(); node != nullptr; node = node->getNext()) {
        if (auto* nodeData = node->getIf<zasm::Data>(); nodeData != nullptr) {
            size += nodeData->getTotalSize();
        } else if (auto* nodeInstr = node->getIf<zasm::Instruction>(); nodeInstr != nullptr) {
            const auto& instrInfo = nodeInstr->getDetail(program.getMode());
            if (instrInfo.hasValue()) {
                size += instrInfo->getLength();
            } else {
                std::cout << "Error: Unable to get instruction info\n";
            }
        } else if (auto* nodeEmbeddedLabel = node->getIf<zasm::EmbeddedLabel>(); nodeEmbeddedLabel != nullptr) {
            const auto bitSize = nodeEmbeddedLabel->getSize();
            if (bitSize == zasm::BitSize::_32)
                size += 4;
            if (bitSize == zasm::BitSize::_64)
                size += 8;
        }
    }
    return size;
}

static void* allocate_page(std::size_t codeSize) {
    return VirtualAlloc(0, codeSize, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
}

int main(int argc, char* argv[]) {
    using namespace zasm;

    Program program(MachineMode::AMD64);
    x86::Assembler a(program);

    {
        auto test_cond = program.createLabel("test_cond");

        a.cmp(x86::rcx, 0x1337);
        a.jz(test_cond);
        a.ret();

        a.bind(test_cond);
        a.nop();
        a.ret();
    }

    const auto estimated_size = estimate_code_size(program);
    void* code_page = allocate_page(estimated_size);

    Serializer serializer;
    if (auto err = serializer.serialize(program, reinterpret_cast<int64_t>(code_page)); err != zasm::Error::None) {
        std::cout << "Serialization failure: " << zasm::getErrorName(err) << "\n";
        return EXIT_FAILURE;
    }

    const auto serialized_size = serializer.getCodeSize();
    std::memcpy(code_page, serializer.getCode(), serialized_size);

    auto fmt_args = disasm::c_instance::fmt_args_t{.data_ptr = (uint8_t*)code_page,
                                                   .address = code_page,
                                                   .dump_opcodes = true,
                                                   .dump_address = true,
                                                   .dump_offset = true};
    logger::info("Generated:\n{}", disasm::get().format_range(fmt_args, estimated_size));

    logger::warn<1>("estimated size: {} | serialized_size: {}", estimated_size, serialized_size);

    return 0;
}
```

The results of executing this function are:
![preview](https://i.imgur.com/iv7TOqr.png)

As you can see, the estimated code size and serialized code size are different because of the `JZ` instruction, which produced the `5 bytes` size instruction at the moment when we were estimating the code size, and it produced the `2 bytes` size instruction at the moment when we were serializing the output, and because of that, the output of my format function produced 2 invalid instructions at the end.

The reason why this happens is that at the moment we are estimating the code size we are encoding instructions one by one and we don't know the addresses of the prev/next instructions, so we can't estimate the relative offset.

Originally I thought about just creating a PR where I fix this, but the more I think the more questions I get. 
Surely we can fix this kind of behaviour for the JMPs/JCCs to the instruction label, but I am not entirely sure how we can calculate the right instruction size if we are dealing with immediate addresses.

**Comment by es3n1n** [comment]
> this is not a bugg

never said it is a bug
i was just hoping for a relevant answer on how to estimate the right size for such instructions, if its even possible. that's it.

**Comment by es3n1n** [comment]
> It is unfortunately not possible to get the accurate size before serialization as the address is not known at the time you query the instruction detail, you have to assume that this is always the worst case. In this particular case its better to over-estimate the size rather than under-estimate so that the buffer size is always big enough to copy the contents.

Fair enough, thanks for replying.

**Comment by ZehMatt** [comment]
By the way, looking at the provided code wouldn't it be enough to pass serialized_size rather than estimated_size when logging?

**Comment by es3n1n** [comment]
> By the way, looking at the provided code wouldn't it be enough to pass serialized_size rather than estimated_size when logging?

Yeah, it's possible and i think i'll do something similar in my JIT stuff anyway, that was just an example

**Comment by ZehMatt** [comment]
> > By the way, looking at the provided code wouldn't it be enough to pass serialized_size rather than estimated_size when logging?
> 
> Yeah, it's possible and i think i'll do something similar in my JIT stuff anyway, that was just an example

Alright, glad that you have some use for this project.
