### ISSUE TITLE
ZydisGetInstructionSegments() in zasm

### ISSUE THREAD

**Issue by NeverEverLol** [zyantific/zasm#102]
I used to use Zydis for a while and recently decided to move to zasm.I am not able to find alternative feature in zasm.Is there is any?

**Comment by NeverEverLol** [comment]
> > you can use `get<Mem>().getSegment()` or when assembling i.e : `assembler.mov(x86::rax, x86::qword_ptr(x86::fs, 0x30)` .
> 
> ZydisGetInstructionSegments is not about memory segmentation, it returns the offsets of the instruction segments.
> 
> > I used to use Zydis for a while and recently decided to move to zasm.I am not able to find alternative feature in zasm.Is there is any?
> 
> zasm doesn't provide this information, how are you using this information? If this is for relocations then zasm already provides that already with the Serialization component.

When I meet instruction like mov,reg,const I need to check whether the const is relocatable iterating the pe header.So I need offset to const.It seems that Serialization component is not what I need,cause it just create raw bytes?

**Comment by NeverEverLol** [comment]
`ZydisInstructionSegments segment;
ZydisGetInstructionSegments(&it->zydis_instr, &segment)
segment.segments[i].type  == ZYDIS_INSTR_SEGMENT_IMMEDIATE`
Some function that can operate the same way

**Comment by ZehMatt** [comment]
Why don't you go by the PE relocation info, this seems like the wrong way about doing it. I'm not exactly sure what your exact use case is but you can obtain relocation info after serialization on zasm in case you want to relocate later.

**Comment by NeverEverLol** [comment]
> Why don't you go by the PE relocation info, this seems like the wrong way about doing it. I'm not exactly sure what your exact use case is but you can obtain relocation info after serialization on zasm in case you want to relocate later.

The problem is i dont use Serualizer at all.I dont need to create a new Program.My purpose is to find out whether imm is relocatable in mov reg,imm.I dont create this instruction myself.Mov reg,imm it is just the instruction I get disassembling bytes(that resides in other file I read before)using Decoder.So Zasm won't generate any RelocInfo cause I simply did not create it myself(using Assembler).The only purpose is to get offset to Imm in for examble mov rbx,Imm(which is 2)And then I iterate in PE header to find if this const is reloc. And file of this pe header locates on my disk.(Sorry for English)

**Comment by ZehMatt** [comment]
> > I understand now. You don't actually need the exact offset for the immediate, you can check if one of the relocation entries intersects with the instruction, you can check if the relocation address is within `[ address, address + instruction length ]` then you can just check if the second operand is an immediate and assume the immediate it is relocatable, if you have two relocation items to the same instruction then it will be for memory operand and immediate. Hope this helps somehow.
> 
> Ahhhh.I did not even think that way despite it is pretty obvious.Thank you for your attention appreciate it. Zasm is so easy to use and your code is so easy readable that in my opinion documentation is redundant.Nevertheless do you have any plans on adding such type of functionality(like ZydisGetInstructionSegment)?

I don't see a lot of reasons to have this information to be honest, I'm trying to avoid having too heavy structures overall and so far I never really needed that information. Another reason I would like to avoid it is as instructions generated by the assembler aren't 100% accurate until they are serialized/encoded, that information would be an estimate at best then. I will however think about it.
