### ISSUE TITLE
Zasm wrong jump calculation

### ISSUE THREAD

**Issue by OptionalAssistant** [zyantific/zasm#115]
Hello,recently I have faced a problem with incorrect jump encoding.Do not think about the sense of the god it is just an example.
` Program program(MachineMode::I386);

 x86::Assembler assembler(program);

 auto label = assembler.createLabel();

 ASSERT_EQ(assembler.jmp(label), Error::None);
 for (int i = 0; i < 100; i++)
     ASSERT_EQ(assembler.nop(), Error::None);
 ASSERT_EQ(assembler.bind(label), Error::None);
 ASSERT_EQ(assembler.int3(), Error::None);
 ASSERT_EQ(assembler.align(Align::Type::Code, 10), Error::None);

Serializer serializer;
 ASSERT_EQ(serializer.serialize(program, 0x0000000000401000), Error::None);`

My jmp should went to int3 instruction but it goes 3 bytes futher.I looked at the source code of zasm and noticed possible incorrect logic(I think).When jmp is encoding first time its size is 5.But on extrapass its value 2(cause now we already have bounded label and it changes from far jmp to short).So now ctx.drift is 3 and we should run pass one more time.But because of aligning at the end of the code drift becomes 0(3 - 3).And now zasm does not run the third pass (despite aligning happens not in range of our jmp)and he thinks that offset of int 3 is still 105 instead of 103.Am I doing something wrong or it is a bug?

P.S.Code is just an example dont take it as smth meaningful.

**Comment by OptionalAssistant** [comment]
Dont pay attention to ASSERT_EQ I just copied some code from google test,rewrite and forgot to delete these macros

**Comment by ZehMatt** [comment]
Thanks for the report, I'll look into it once I get a bit of time.

**Comment by ZehMatt** [comment]
Should be fixed, thanks again.

**Comment by OptionalAssistant** [comment]
Sorry to be late.But may we remove ctx.drift calculation and variable itself?Zasm never uses drift anymore?Or you are planning to rewrite code to use drift in the end?

**Comment by OptionalAssistant** [comment]
I mean calculation at lines   135 140 173 178 and drift variable declaration at line 506 ?
