### ISSUE TITLE
Mem constructor for [base + index]

### ISSUE THREAD

**Issue by TACIXAT** [zyantific/zasm#124]
Should the Mem constructor that takes base and index registers have scale set to 1 instead of 0?

https://github.com/zyantific/zasm/blob/012062f573ac6e26fe22c62192426b84ef54c2aa/include/zasm/x86/memory.hpp#L27

Succeeds:

```c++
a.mov(zasm::x86::al, zasm::x86::byte_ptr(zasm::x86::rsi, zasm::x86::rcx, 1, 0));
```

Fails impossible instruction:

```c++
a.mov(zasm::x86::al, zasm::x86::byte_ptr(zasm::x86::rsi, zasm::x86::rcx));
```

Likely cause: 

```c++
    // ptr [base + index]
    // ex.: mov eax, ptr [ecx+edx]
    static constexpr Mem ptr(BitSize bitSize, const Gp& base, const Gp& index) noexcept
    {
        return Mem(bitSize, Seg{}, base, index, 0, 0);
    }
```

**Comment by ZehMatt** [comment]
I will have to look into that, I remember there was a special case about this.

**Comment by ZehMatt** [comment]
I've merged the change so its now 1 by default when index is supplied, thanks for the reporting the issue.
