### ISSUE TITLE
jmp imm bug

### ISSUE THREAD

**Issue by blackchicken20** [zyantific/zasm#129]
![Snipaste_2024-06-07_13-27-47](https://github.com/zyantific/zasm/assets/58726436/72a88701-7dc9-4e83-9e07-e274f67472c5)
My target address is 0x347486 (0x224AB8A1486), but the generated assembly instruction's target address is 0x347485 (0x224AB8A1485). Is this a bug?

```
    zasm::Program program(zasm::MachineMode::AMD64);
    zasm::x86::Assembler assembler(program);

    assembler.jmp(zasm::Imm(instr.jmp_rva));

    zasm::Serializer serializer{};
    auto res = serializer.serialize(program, instr.rva);
    if (res == zasm::ErrorCode::None) {
      auto ptr = serializer.getCode();
      auto size = serializer.getCodeSize();
      std::memcpy(reinterpret_cast<void *>(base.module_base + instr.rva),
                  serializer.getCode(), serializer.getCodeSize());
     }
     
```

**Comment by ZehMatt** [comment]
I've created a small test function using the information you provided.
```cpp
    TEST(SerializationTests, Issue_129)
    {
        int64_t rva = 0x3471fe;
        int64_t jmp_rva = 0x347486;

        Program program(zasm::MachineMode::AMD64);
        x86::Assembler assembler(program);

        assembler.jmp(zasm::Imm(jmp_rva));

        zasm::Serializer serializer{};
        auto res = serializer.serialize(program, rva);
        if (res == zasm::ErrorCode::None)
        {
            auto ptr = serializer.getCode();
            auto size = serializer.getCodeSize();

            ASSERT_EQ(size, 5);

            auto decoder = zasm::Decoder(zasm::MachineMode::AMD64);
            auto decoded = decoder.decode(ptr, size, rva);

            auto& op0 = decoded->getOperand<Imm>(0);
            ASSERT_EQ(op0.value<int64_t>(), jmp_rva);
        }
    }
```
This test however passes on my end, the expected immediate has the value 0x347486. Are you using the latest commit?

**Comment by blackchicken20** [comment]
> I've created a small test function using the information you provided.
> 
> ```c++
>     TEST(SerializationTests, Issue_129)
>     {
>         int64_t rva = 0x3471fe;
>         int64_t jmp_rva = 0x347486;
> 
>         Program program(zasm::MachineMode::AMD64);
>         x86::Assembler assembler(program);
> 
>         assembler.jmp(zasm::Imm(jmp_rva));
> 
>         zasm::Serializer serializer{};
>         auto res = serializer.serialize(program, rva);
>         if (res == zasm::ErrorCode::None)
>         {
>             auto ptr = serializer.getCode();
>             auto size = serializer.getCodeSize();
> 
>             ASSERT_EQ(size, 5);
> 
>             auto decoder = zasm::Decoder(zasm::MachineMode::AMD64);
>             auto decoded = decoder.decode(ptr, size, rva);
> 
>             auto& op0 = decoded->getOperand<Imm>(0);
>             ASSERT_EQ(op0.value<int64_t>(), jmp_rva);
>         }
>     }
> ```
> 
> This test however passes on my end, the immediate has the expected value 0x347486. Are you using the latest commit?



> I've created a small test function using the information you provided.
> 
> ```c++
>     TEST(SerializationTests, Issue_129)
>     {
>         int64_t rva = 0x3471fe;
>         int64_t jmp_rva = 0x347486;
> 
>         Program program(zasm::MachineMode::AMD64);
>         x86::Assembler assembler(program);
> 
>         assembler.jmp(zasm::Imm(jmp_rva));
> 
>         zasm::Serializer serializer{};
>         auto res = serializer.serialize(program, rva);
>         if (res == zasm::ErrorCode::None)
>         {
>             auto ptr = serializer.getCode();
>             auto size = serializer.getCodeSize();
> 
>             ASSERT_EQ(size, 5);
> 
>             auto decoder = zasm::Decoder(zasm::MachineMode::AMD64);
>             auto decoded = decoder.decode(ptr, size, rva);
> 
>             auto& op0 = decoded->getOperand<Imm>(0);
>             ASSERT_EQ(op0.value<int64_t>(), jmp_rva);
>         }
>     }
> ```
> 
> This test however passes on my end, the immediate has the expected value 0x347486. Are you using the latest commit?

yes,i use latest commit.

![Snipaste_2024-06-08_10-09-10](https://github.com/zyantific/zasm/assets/58726436/313c4ffe-40ed-4394-843b-f204865d790a)

**Comment by blackchicken20** [comment]
I created a new project, pulled the commit again, recompiled, and the issue was resolved.
thks @ZehMatt .

**Comment by ZehMatt** [comment]
Glad it worked out, for good measure I added a new test #130 based on this to prevent such an issue in the future.
