### ISSUE TITLE
Serializer reports "Impossible instruction" error with valid instruction

### ISSUE THREAD

**Issue by never-unsealed** [zyantific/zasm#138]
Hello,

I compiled Zasm from source code 4 days ago using latest Visual Studio 2022 (CMake tools) on Windows 11.
When using the Assembler class, I noticed a strange behavior where serializing would fail with error "Impossible instruction" even though the instruction is valid. 

This behavior should be reproducible with following code (using latest MSVC for compilation):

```c
#include "zasm/formatter/formatter.hpp"
#include "zasm.hpp"

#include <stdio.h>
int main()
{
    using namespace zasm;
    using namespace zasm::x86;

    Program     Program(MachineMode::AMD64);
    Assembler   Assembler(Program);
    Serializer  Serializer;
    Error       ZasmError;

    Assembler.mov(ecx, Imm(0xFFFFFFFF));

    ZasmError = Serializer.serialize(Program, 0);

    if (ZasmError.getCode() != ErrorCode::None)
    {
        printf("%s\n", ZasmError.getErrorMessage()); // This line gets hit: "Error at node "mov ecx, 0xffffffff" with id 0: Impossible instruction"
        exit(1);
    }

    exit(0);
}
```

When setting the immediate value to a slightly lower value (for example 0x1FFFFFFF), there is no error.

**Comment by ZehMatt** [comment]
The issue is that 0xFFFFFFFF is uint32_t but the operand is expected to be int32_t, you can use Imm32 or use -1.
