### ISSUE TITLE
memory bug while deleting label with destroyNode

### ISSUE THREAD

**Issue by qcold** [zyantific/zasm#140]
when creating a label we see the following code:
```
static Label createLabel_(detail::ProgramState& state, StringPool::Id nameId, StringPool::Id modId, LabelFlags flags)
    {
        const auto labelId = static_cast<Label::Id>(state.labels.size());

        auto& entry = state.labels.emplace_back();
        entry.id = labelId;
        entry.flags = flags;
        entry.nameId = nameId;
        entry.moduleId = modId;

        return Label{ labelId };
    }
```
here we are adding a label to the label list but when we want to destroy the label node using destroyNode method the label list is not decremented
```
static void destroyNode(detail::ProgramState& state, Node* node, bool quickDestroy)
    {
        // Keep index before destroying the object.
        const auto nodeIdx = static_cast<std::size_t>(node->getId());

        notifyObservers<true>(&Observer::onNodeDestroy, state.observer, node);

        // If this is called from clear or from destructor we can skip unlinking.
        if (!quickDestroy)
        {
            // Ensure node is not in the list anymore.
            detach_<false>(node, state);
        }

        // Release.
        auto* nodeToDestroy = detail::toInternal(node);
        state.nodePool.destroy(nodeToDestroy);

        if (!quickDestroy)
        {
            // Release memory, when quickDestroy is true the entire pool will be cleared at once.
            state.nodePool.deallocate(nodeToDestroy, 1);

            // Remove mapping.
            auto& nodeMap = state.nodeMap;
            assert(nodeIdx < nodeMap.size());

            // Null out the slot.
            nodeMap[nodeIdx] = nullptr;

            while (!nodeMap.empty() && nodeMap.back() == nullptr)
            {
                nodeMap.pop_back();
            }
        }
    }

    void Program::destroy(Node* node)
    {
        destroyNode(*_state, node, false);
    }
```
here we don't see a descending list of tags. Is this a bug or am I missing something?

**Comment by ZehMatt** [comment]
Labels are not destroyed on purpose as other nodes can still reference it. If you want to really clear the Program you have to call clear.

**Comment by qcold** [comment]
> Labels are not destroyed on purpose as other nodes can still reference it. If you want to really clear the Program you have to call clear.

I am doing optimizations with your project and I need to delete not all labels, but only some. Can I try to add such functionality?

**Comment by qcold** [comment]
e.g. if we delete jmp instruction, then we also should delete label of that jump. am i right?

**Comment by ZehMatt** [comment]
You can only delete labels that have no references. The complexity to track the label references like that automatically is too big as you can also modify the Instruction operands at any given time which the Program is unaware of. Are you running into memory issues? I'm not really seeing a big issue here to be honest.

**Comment by qcold** [comment]
> You can only delete labels that have no references. The complexity to track the label references like that automatically is too big as you can also modify the Instruction operands at any given time which the Program is unaware of. Are you running into memory issues? I'm not really seeing a big issue here to be honest.

i understand you, I have a concern that if my optimization pass goes through 100 iterations and there are at least 10 jumps in one function, I will lose a lot of memory. Because this pass simplifies branches by erasing labels and setting another label of the same instruction.

**Comment by ZehMatt** [comment]
Creating 10'000'000 labels costs only 276 MiB, which is not a lot really. I will close this issue as I currently see no problem here.
