### ISSUE TITLE
Could you bind for go language?

### ISSUE THREAD

**Issue by ddkwork** [zyantific/zasm#27]

**Comment by ZehMatt** [comment]
I have no experience with Go so I have to say no unless someone is willing to contribute them.

**Comment by ddkwork** [comment]
Sorry my bad English. My means's is text assembly like

https://github.com/ddkwork/xed/blob/master/parse_test.go

**Comment by ZehMatt** [comment]
zasm has no parser so that is also not possible.

**Comment by ddkwork** [comment]
oh, thx
