### ISSUE TITLE
More basic examples needed

### ISSUE THREAD

**Issue by differentprogramming** [zyantific/zasm#57]
I asked before for the ability to get the address of a label, and you supplied that.

Now I need a few other things:
Examples of basic things
a) actually calling code you assembled.  There are no examples of calling code you created.
b) an example of calling into user or library code from assembly.
c) disassembling to human readable form.  Getting the abi right for a platform is complex, and you pretty much need to be able to disassemble and see code that the compiler generates so that you can make templates from entry and exit code that's correct in every detail.  Also it would be useful for making sure that the code you're generating is what you thought it was.
d) deallocating the result of an assembly - for a jit you not only create code, but you throw it away when you're done with it and are replacing it with altered code.

Edit I guess I can just use the debugger for disassembly.

**Comment by ZehMatt** [comment]
a.) If you want to call your the code you assembled you just have to copy the code into an executable memory region and cast that to a function pointer to call it, this should be already possible there is also a way of relocating the code to a different base address.
b.) There is an example here actually https://github.com/ZehMatt/zasm-modules/blob/master/src/example/main.cpp this calls MessageBoxA, getting into ABI things is already too high-level.
c.) You can actually print the Instruction or Nodes or the entire Program with the formatter code, see https://github.com/zyantific/zasm/blob/bceca25e7780bda145c631b34302304b899ef567/include/zasm/formatter/formatter.hpp#L60

Something to keep in mind is that zasm is not supposed to be a high level compiler, so generating functions and invoking them is up to the user. zasm as is currently acts more as a foundation to be able to build high level things on-top, the zasm-modules project would be an example.

**Comment by differentprogramming** [comment]
Yes I know that the ABI is my problem, not Zasm's

**Comment by differentprogramming** [comment]
So it doesn't create assemble into executable memory?  I have to create that with VirtualAlloc then copy the code?

How do I copy the code?

**Comment by ZehMatt** [comment]
std::memcpy should do the trick, keep in mind to call relocateTo to the new base address before copying or specify the base address beforehand.

**Comment by ZehMatt** [comment]
You can also look at https://github.com/zyantific/zasm/blob/master/src/tests/tests/tests.relocation.cpp for reference on relocations

**Comment by ZehMatt** [comment]
I hope I answered all the questions.
